using Microsoft.AspNetCore.Mvc;
using TUPMundial.Web.Services;

namespace TUPMundial.Web.Controllers
{
    public class AuthController : Controller
        {
                private readonly MundialService _service;
                        public AuthController(MundialService service) => _service = service;

                                // GET /Auth/Login
                                        public IActionResult Login() => View();

                                                // POST /Auth/Login
                                                        [HttpPost]
                                                                public IActionResult Login(string email, string password)
                                                                        {
                                                                                    if (string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password))
                                                                                                {
                                                                                                                ViewBag.Error = "Completá todos los campos";
                                                                                                                                return View();
                                                                                                                                            }
                                                                                                                                                        if (!System.Text.RegularExpressions.Regex.IsMatch(email, @"^[^@\s]+@[^@\s]+\.[^@\s]+$"))
                                                                                                                                                                    {
                                                                                                                                                                                    ViewBag.Error = "El email no es válido";
                                                                                                                                                                                                    return View();
                                                                                                                                                                                                                }
                                                                                                                                                                                                                            if (_service.Login(email, password, out var usuario))
                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                        HttpContext.Session.SetString("UsuarioEmail", usuario!.Email);
                                                                                                                                                                                                                                                                        HttpContext.Session.SetString("UsuarioNombre", usuario!.Nombre);
                                                                                                                                                                                                                                                                                        return RedirectToAction("Index", "Partidos");
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                ViewBag.Error = "Email o contraseña incorrectos";
                                                                                                                                                                                                                                                                                                                            return View();
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                            // GET /Auth/Registro
                                                                                                                                                                                                                                                                                                                                                    public IActionResult Registro() => View();

                                                                                                                                                                                                                                                                                                                                                            // POST /Auth/Registro
                                                                                                                                                                                                                                                                                                                                                                    [HttpPost]
                                                                                                                                                                                                                                                                                                                                                                            public IActionResult Registro(string nombre, string email, string password, string password2)
                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                if (string.IsNullOrEmpty(nombre) || string.IsNullOrEmpty(email) ||
                                                                                                                                                                                                                                                                                                                                                                                                                string.IsNullOrEmpty(password) || string.IsNullOrEmpty(password2))
                                                                                                                                                                                                                                                                                                                                                                                                                            { ViewBag.Error = "Completá todos los campos"; return View(); }

                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!System.Text.RegularExpressions.Regex.IsMatch(email, @"^[^@\s]+@[^@\s]+\.[^@\s]+$"))
                                                                                                                                                                                                                                                                                                                                                                                                                                                    { ViewBag.Error = "El email no es válido"; return View(); }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (password.Length < 6)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { ViewBag.Error = "La contraseña debe tener al menos 6 caracteres"; return View(); }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (password != password2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { ViewBag.Error = "Las contraseñas no coinciden"; return View(); }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var error = _service.Registro(nombre, email, password);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (error != null) { ViewBag.Error = error; return View(); }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Login automático tras registrarse
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _service.Login(email, password, out var usuario);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                HttpContext.Session.SetString("UsuarioEmail", usuario!.Email);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            HttpContext.Session.SetString("UsuarioNombre", usuario!.Nombre);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return RedirectToAction("Index", "Partidos");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // GET /Auth/Logout
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public IActionResult Logout()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    HttpContext.Session.Clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return RedirectToAction("Login");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }