using Microsoft.AspNetCore.Mvc;
using TUPMundial.Web.Services;

namespace TUPMundial.Web.Controllers
{
    public class TicketsController : Controller
        {
                private readonly MundialService _service;
                        public TicketsController(MundialService service) => _service = service;

                                private string? Email => HttpContext.Session.GetString("UsuarioEmail");
                                        private bool EstaLogueado() => !string.IsNullOrEmpty(Email);

                                                // GET /Tickets
                                                        public IActionResult Index()
                                                                {
                                                                            if (!EstaLogueado()) return RedirectToAction("Login", "Auth");
                                                                                        var tickets = _service.ObtenerTicketsUsuario(Email!);
                                                                                                    ViewBag.TotalEntradas = tickets.Sum(t => t.Cantidad);
                                                                                                                ViewBag.TotalGastado  = tickets.Sum(t => t.Total);
                                                                                                                            return View(tickets);
                                                                                                                                    }

                                                                                                                                            // GET /Tickets/Comprar/5
                                                                                                                                                    public IActionResult Comprar(int id)
                                                                                                                                                            {
                                                                                                                                                                        if (!EstaLogueado()) return RedirectToAction("Login", "Auth");
                                                                                                                                                                                    var partido = _service.ObtenerPartidoPorId(id);
                                                                                                                                                                                                if (partido == null) return RedirectToAction("Index", "Partidos");
                                                                                                                                                                                                            return View(partido);
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                            // POST /Tickets/Comprar
                                                                                                                                                                                                                                    [HttpPost]
                                                                                                                                                                                                                                            public IActionResult Comprar(int partidoId, string sector, int cantidad, decimal precioUnit)
                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                if (!EstaLogueado()) return RedirectToAction("Login", "Auth");

                                                                                                                                                                                                                                                                            if (string.IsNullOrEmpty(sector) || cantidad < 1 || precioUnit <= 0)
                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                        var partido = _service.ObtenerPartidoPorId(partidoId);
                                                                                                                                                                                                                                                                                                                        ViewBag.Error = "Seleccioná un sector válido";
                                                                                                                                                                                                                                                                                                                                        return View(partido);
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                _service.ComprarTicket(Email!, partidoId, sector, cantidad, precioUnit);
                                                                                                                                                                                                                                                                                                                                                                            return RedirectToAction("Confirmacion", new { partidoId, sector, cantidad, precioUnit });
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                            // GET /Tickets/Confirmacion
                                                                                                                                                                                                                                                                                                                                                                                                    public IActionResult Confirmacion(int partidoId, string sector, int cantidad, decimal precioUnit)
                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                        if (!EstaLogueado()) return RedirectToAction("Login", "Auth");
                                                                                                                                                                                                                                                                                                                                                                                                                                    var partido = _service.ObtenerPartidoPorId(partidoId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                ViewBag.Sector     = sector;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ViewBag.Cantidad   = cantidad;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ViewBag.PrecioUnit = precioUnit;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ViewBag.Total      = precioUnit * cantidad;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return View(partido);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }