using TUPMundial.Web.Models;

namespace TUPMundial.Web.Services
{
    public class MundialService
        {
                // ── Datos de prueba (después se reemplazan por llamadas a la API) ──
                        private static List<Partido> _partidos = new()
                                {
                                            new Partido { Id=1, Equipo1="México", Equipo2="Sudáfrica", Fecha="11/06/2026 15:00 hs", Grupo="Grupo A", Estadio="Estadio Azteca (CDMX)", Precio="USD 160 - USD 360", Flag1="🇲🇽", Flag2="🇿🇦" },
                                                        new Partido { Id=2, Equipo1="Corea del Sur", Equipo2="República Checa", Fecha="11/06/2026 20:00 hs", Grupo="Grupo A", Estadio="Estadio Akron (Guadalajara)", Precio="USD 120 - USD 280", Flag1="🇰🇷", Flag2="🇨🇿" },
                                                                    new Partido { Id=3, Equipo1="Canadá", Equipo2="Bosnia", Fecha="12/06/2026 15:00 hs", Grupo="Grupo B", Estadio="BMO Field (Toronto)", Precio="USD 140 - USD 320", Flag1="🇨🇦", Flag2="🇧🇦" },
                                                                                new Partido { Id=4, Equipo1="Estados Unidos", Equipo2="Paraguay", Fecha="12/06/2026 21:00 hs", Grupo="Grupo D", Estadio="SoFi Stadium (Los Ángeles)", Precio="USD 200 - USD 500", Flag1="🇺🇸", Flag2="🇵🇾" },
                                                                                            new Partido { Id=5, Equipo1="Francia", Equipo2="Senegal", Fecha="16/06/2026 15:00 hs", Grupo="Grupo I", Estadio="MetLife Stadium (NY/NJ)", Precio="USD 180 - USD 420", Flag1="🇫🇷", Flag2="🇸🇳" },
                                                                                                        new Partido { Id=6, Equipo1="Alemania", Equipo2="Curazao", Fecha="14/06/2026 15:00 hs", Grupo="Grupo E", Estadio="NRG Stadium (Houston)", Precio="USD 150 - USD 350", Flag1="🇩🇪", Flag2="🇨🇼" },
                                                                                                                    new Partido { Id=7, Equipo1="Argentina", Equipo2="Polonia", Fecha="15/06/2026 18:00 hs", Grupo="Grupo C", Estadio="Rose Bowl (Los Ángeles)", Precio="USD 220 - USD 550", Flag1="🇦🇷", Flag2="🇵🇱" },
                                                                                                                                new Partido { Id=8, Equipo1="Brasil", Equipo2="Suiza", Fecha="16/06/2026 21:00 hs", Grupo="Grupo F", Estadio="Allegiant Stadium (Las Vegas)", Precio="USD 200 - USD 480", Flag1="🇧🇷", Flag2="🇨🇭" },
                                                                                                                                            new Partido { Id=9, Equipo1="España", Equipo2="Croacia", Fecha="17/06/2026 15:00 hs", Grupo="Grupo G", Estadio="AT&T Stadium (Dallas)", Precio="USD 170 - USD 400", Flag1="🇪🇸", Flag2="🇭🇷" },
                                                                                                                                                        new Partido { Id=10, Equipo1="Portugal", Equipo2="Marruecos", Fecha="18/06/2026 19:00 hs", Grupo="Grupo H", Estadio="Levi's Stadium (San Francisco)", Precio="USD 190 - USD 440", Flag1="🇵🇹", Flag2="🇲🇦" },
                                                                                                                                                                };

                                                                                                                                                                        private static List<Usuario> _usuarios = new();
                                                                                                                                                                                private static List<Ticket> _tickets = new();

                                                                                                                                                                                        // ── Partidos ──
                                                                                                                                                                                                public List<Partido> ObtenerPartidos(string? grupo = null)
                                                                                                                                                                                                        {
                                                                                                                                                                                                                    if (string.IsNullOrEmpty(grupo) || grupo == "Todos")
                                                                                                                                                                                                                                    return _partidos;
                                                                                                                                                                                                                                                return _partidos.Where(p => p.Grupo == grupo).ToList();
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                public Partido? ObtenerPartidoPorId(int id) =>
                                                                                                                                                                                                                                                                            _partidos.FirstOrDefault(p => p.Id == id);

                                                                                                                                                                                                                                                                                    public List<string> ObtenerGrupos() =>
                                                                                                                                                                                                                                                                                                _partidos.Select(p => p.Grupo).Distinct().OrderBy(g => g).ToList();

                                                                                                                                                                                                                                                                                                        // ── Auth ──
                                                                                                                                                                                                                                                                                                                public bool Login(string email, string password, out Usuario? usuario)
                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                    var hash = HashPassword(password);
                                                                                                                                                                                                                                                                                                                                                usuario = _usuarios.FirstOrDefault(u => u.Email == email && u.PasswordHash == hash);
                                                                                                                                                                                                                                                                                                                                                            return usuario != null;
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                            public string? Registro(string nombre, string email, string password)
                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                if (_usuarios.Any(u => u.Email == email))
                                                                                                                                                                                                                                                                                                                                                                                                                return "El email ya está registrado";
                                                                                                                                                                                                                                                                                                                                                                                                                            _usuarios.Add(new Usuario
                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Id = _usuarios.Count + 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Nombre = nombre,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Email = email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        PasswordHash = HashPassword(password)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return null; // null = éxito
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ── Tickets ──
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public List<Ticket> ObtenerTicketsUsuario(string email) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _tickets.Where(t => t.UsuarioEmail == email).ToList();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public void ComprarTicket(string email, int partidoId, string sector, int cantidad, decimal precioUnit)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var partido = ObtenerPartidoPorId(partidoId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (partido == null) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _tickets.Add(new Ticket
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Id = _tickets.Count + 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    UsuarioEmail = email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    PartidoId = partidoId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Equipo1 = partido.Equipo1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Equipo2 = partido.Equipo2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Fecha = partido.Fecha,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Estadio = partido.Estadio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Grupo = partido.Grupo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Sector = sector,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Cantidad = cantidad,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    PrecioUnit = precioUnit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Total = precioUnit * cantidad
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private static string HashPassword(string password)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    using var sha = System.Security.Cryptography.SHA256.Create();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var bytes = sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(password));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return Convert.ToHexString(bytes).ToLower();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }